/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx,html}'],
  theme: {
    extend: {
      colors: {
        'primary-fixed': '#98f1f8',
        'inverse-surface': '#dae3ef',
        'primary-container': '#0c7c83',
        'on-secondary-fixed-variant': '#2e4966',
        background: '#0b141c',
        tertiary: '#ffb86b',
        'on-tertiary-container': '#fff3ea',
        'on-primary-fixed-variant': '#004f54',
        'surface-container-high': '#222b33',
        'on-primary-container': '#d6fcff',
        'secondary-container': '#2e4966',
        'on-secondary-fixed': '#001d36',
        'on-tertiary': '#492900',
        'on-secondary': '#16324e',
        'surface-container-highest': '#2d363e',
        'on-surface-variant': '#bdc9c9',
        'on-secondary-container': '#9db7da',
        surface: '#0b141c',
        'on-surface': '#dae3ef',
        'surface-bright': '#313a43',
        'on-tertiary-fixed': '#2c1700',
        'tertiary-container': '#a16100',
        'tertiary-fixed': '#ffdcbc',
        'error-container': '#93000a',
        'secondary-fixed-dim': '#aec9ec',
        secondary: '#aec9ec',
        'surface-container-low': '#141c25',
        'surface-dim': '#0b141c',
        'on-primary-fixed': '#002022',
        'inverse-on-surface': '#28313a',
        'tertiary-fixed-dim': '#ffb86b',
        'inverse-primary': '#00696f',
        'primary-fixed-dim': '#7bd4dc',
        'secondary-fixed': '#d1e4ff',
        primary: '#7bd4dc',
        error: '#ffb4ab',
        'outline-variant': '#3e494a',
        'surface-tint': '#7bd4dc',
        'on-primary': '#00363a',
        'surface-container': '#182029',
        'surface-variant': '#2d363e',
        'surface-container-lowest': '#060f17',
        'on-background': '#dae3ef',
        outline: '#889394',
        'on-error-container': '#ffdad6',
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#683d00',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'gutter-desktop': '1rem',
        'space-lg': '1rem',
        'space-xl': '1.5rem',
        'margin-desktop': '1.5rem',
        'space-xs': '0.25rem',
        'space-md': '0.75rem',
        margin: '1rem',
        gutter: '0.75rem',
      },
      fontFamily: {
        'label-lg': ['IBM Plex Sans', 'sans-serif'],
        'body-lg': ['IBM Plex Sans', 'sans-serif'],
        'headline-xl-mobile': ['IBM Plex Sans', 'sans-serif'],
        'body-sm': ['IBM Plex Sans', 'sans-serif'],
        'telemetry-lg': ['IBM Plex Mono', 'monospace'],
        'label-md': ['IBM Plex Sans', 'sans-serif'],
        'headline-lg': ['IBM Plex Sans', 'sans-serif'],
        'headline-sm': ['IBM Plex Sans', 'sans-serif'],
        'telemetry-sm': ['IBM Plex Mono', 'monospace'],
        'headline-md': ['IBM Plex Sans', 'sans-serif'],
        'body-md': ['IBM Plex Sans', 'sans-serif'],
        'headline-xl': ['IBM Plex Sans', 'sans-serif'],
        'label-sm': ['IBM Plex Sans', 'sans-serif'],
        'telemetry-md': ['IBM Plex Mono', 'monospace'],
        'headline-lg-mobile': ['IBM Plex Sans', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.04em', fontWeight: '600' }],
        'body-lg': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'headline-xl-mobile': ['1.5rem', { lineHeight: '2rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-sm': ['0.75rem', { lineHeight: '1.125rem', fontWeight: '400' }],
        'telemetry-lg': ['1.25rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '500' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.06em', fontWeight: '600' }],
        'headline-lg': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-sm': ['1.05rem', { lineHeight: '1.5rem', letterSpacing: '0em', fontWeight: '600' }],
        'telemetry-sm': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0em', fontWeight: '400' }],
        'headline-md': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'headline-xl': ['2.25rem', { lineHeight: '2.75rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['0.6875rem', { lineHeight: '0.875rem', letterSpacing: '0.08em', fontWeight: '600' }],
        'telemetry-md': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0em', fontWeight: '500' }],
        'headline-lg-mobile': ['1.25rem', { lineHeight: '1.75rem', letterSpacing: '0em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
